test_analytics_engineering:
  outputs:
    dev:
      dataset: StageDeaAnalytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: southamerica-west1
      method: oauth
      priority: interactive
      project: fresh-catwalk-438015-b4
      threads: 1
      type: bigquery
  target: dev